name: zef_helpers_lazy
description: A Dart package providing a versatile implementation of lazy initialization.
version: 2.0.0
homepage: https://www.zooper.dev
repository: https://github.com/zooper-lib/ZEF_Helpers_Lazy
topics:
  - lazy
funding:
  - https://buymeacoffee.com/zooperlib

environment:
  sdk: ^3.0.5

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
